### ISSUE TITLE
Exception: Error reading camera data: CALIBRATION FILE NOT AVAILABLE

### ISSUE THREAD

**Issue by mumianyuxin** [rerun-io/python-example-droid-dataset#10]
Thanks for your great work. I try to get the intrinsic matrix of cameras in SVO, following the tutorial in `Viewing the raw dataset with depth images (requires CUDA)`, but I get the error:
```
[2024-11-20 02:43:39 UTC][ZED][INFO] Logging level INFO
[2024-11-20 02:43:39 UTC][ZED][INFO] [Init]  Depth mode: QUALITY
[2024-11-20 02:43:39 UTC][ZED][INFO] [Init]  Serial Number: S/N 23897859
[2024-11-20 02:43:39 UTC][ZED][INFO] [Init]  No calibration file found for SN 23897859. Downloading...
[2024-11-20 02:43:40 UTC][ZED][INFO] [Init]  Unable to download calibration file.
 * Option 1: Launch ZED Explorer App with --dc 23897859
 * Option 2: Download your calibration file on https://calib.stereolabs.com
[2024-11-20 02:43:40 UTC][ZED][WARNING] CALIBRATION FILE NOT AVAILABLE in sl::ERROR_CODE sl::Camera::open(sl::InitParameters)
Traceback (most recent call last):
  File "/root/droid-example/src/raw.py", line 426, in <module>
    main()
  File "/root/droid-example/src/raw.py", line 421, in main
    raw_scene = RawScene(args.scene)
  File "/root/droid-example/src/raw.py", line 153, in __init__
    cam = StereoCamera(
  File "/root/droid-example/src/raw.py", line 41, in __init__
    raise Exception(f"Error reading camera data: {err}")
Exception: Error reading camera data: CALIBRATION FILE NOT AVAILABLE
[2024-11-20 02:43:40 UTC][ZED][ERROR] [ZED] sl::Camera::Open has not been called, no Camera instance running.
[2024-11-20 02:43:40 UTC][ZED][ERROR] [ZED] sl::Camera::Open has not been called, no Camera instance running.
```

**Comment by mumianyuxin** [comment]
I solved that after downloading the calibration file. Thanks.
