### ISSUE TITLE
Something wrong about running src/rld.py command.

### ISSUE THREAD

**Issue by CRLqinliang** [rerun-io/python-example-droid-dataset#5]
Hi, when I run this command
`src/rlds.py`

Then I got this response:

> Unknown attribute "D" in /robot[@name='panda']/joint[@name='panda_joint1']/dynamics
Unknown attribute "K" in /robot[@name='panda']/joint[@name='panda_joint1']/dynamics
Unknown attribute "mu_coulomb" in /robot[@name='panda']/joint[@name='panda_joint1']/dynamics
Unknown attribute "mu_viscous" in /robot[@name='panda']/joint[@name='panda_joint1']/dynamics
Unknown attribute "D" in /robot[@name='panda']/joint[@name='panda_joint2']/dynamics
Unknown attribute "K" in /robot[@name='panda']/joint[@name='panda_joint2']/dynamics
Unknown attribute "mu_coulomb" in /robot[@name='panda']/joint[@name='panda_joint2']/dynamics
Unknown attribute "mu_viscous" in /robot[@name='panda']/joint[@name='panda_joint2']/dynamics
Unknown attribute "D" in /robot[@name='panda']/joint[@name='panda_joint3']/dynamics
Unknown attribute "K" in /robot[@name='panda']/joint[@name='panda_joint3']/dynamics
Unknown attribute "mu_coulomb" in /robot[@name='panda']/joint[@name='panda_joint3']/dynamics
Unknown attribute "mu_viscous" in /robot[@name='panda']/joint[@name='panda_joint3']/dynamics
Unknown attribute "D" in /robot[@name='panda']/joint[@name='panda_joint4']/dynamics
Unknown attribute "K" in /robot[@name='panda']/joint[@name='panda_joint4']/dynamics
Unknown attribute "mu_coulomb" in /robot[@name='panda']/joint[@name='panda_joint4']/dynamics
Unknown attribute "mu_viscous" in /robot[@name='panda']/joint[@name='panda_joint4']/dynamics
Unknown attribute "D" in /robot[@name='panda']/joint[@name='panda_joint5']/dynamics
Unknown attribute "K" in /robot[@name='panda']/joint[@name='panda_joint5']/dynamics
Unknown attribute "mu_coulomb" in /robot[@name='panda']/joint[@name='panda_joint5']/dynamics
Unknown attribute "mu_viscous" in /robot[@name='panda']/joint[@name='panda_joint5']/dynamics
Unknown attribute "D" in /robot[@name='panda']/joint[@name='panda_joint6']/dynamics
Unknown attribute "K" in /robot[@name='panda']/joint[@name='panda_joint6']/dynamics
Unknown attribute "mu_coulomb" in /robot[@name='panda']/joint[@name='panda_joint6']/dynamics
Unknown attribute "mu_viscous" in /robot[@name='panda']/joint[@name='panda_joint6']/dynamics
Unknown attribute "D" in /robot[@name='panda']/joint[@name='panda_joint7']/dynamics
Unknown attribute "K" in /robot[@name='panda']/joint[@name='panda_joint7']/dynamics
Unknown attribute "mu_coulomb" in /robot[@name='panda']/joint[@name='panda_joint7']/dynamics
Unknown attribute "mu_viscous" in /robot[@name='panda']/joint[@name='panda_joint7']/dynamics
No scene picked, downloads the droid_100 dataset, might be a bit slow!
thread 'ThreadId(1)' panicked at 'called `Option::unwrap()` on a `None` value'
wgpu-core-0.19.3/src/instance.rs:521
stack backtrace:
   6: core::panicking::panic_fmt
             at core/src/panicking.rs:72:14
   7: core::panicking::panic
             at core/src/panicking.rs:127:5
   8: wgpu_core::instance::<impl wgpu_core::global::Global<G>>::instance_create_surface
   9: <T as wgpu::context::DynContext>::instance_create_surface
  10: wgpu::Instance::create_surface_unsafe
Troubleshooting Rerun: https://www.rerun.io/docs/getting-started/troubleshooting
Report bugs: https://github.com/rerun-io/rerun/issues
[2024-04-30T07:41:14Z WARN  re_sdk_comms::buffered_client] Failed to send message after 3 attempts: Failed to send to Rerun server at 127.0.0.1:9876: Broken pipe (os error 32)
[2024-04-30T07:41:17Z WARN  re_sdk_comms::buffered_client] Dropping messages because tcp client has timed out.
[2024-04-30T07:41:17Z WARN  re_sdk_comms::buffered_client] Dropping messages because tcp client has timed out.
[2024-04-30T07:54:21Z WARN  re_sdk_comms::tcp_client] Tried to flush while TCP stream was still Pending. Data was possibly dropped.

Please have a check, thanks.

**Comment by Wumpf** [comment]
This is a duplicate of

* https://github.com/rerun-io/rerun/issues/5968

I'm working on a fix but we still have a pretty unclear picture of when this crash occurs as it happens only in a few select setups, mostly inside containers. In what environment are you trying to run Rerun? (OS, gpu, driver, window manager)

**Comment by CRLqinliang** [comment]
@Wumpf Thanks for the reply!
OS: WSL2 
GPU: RTX4090
Driver: CUDA12.2
Env: conda virtual env (not docker)

**Comment by Wumpf** [comment]
@CRLqinliang have you tried any of  the advice in https://www.rerun.io/docs/getting-started/troubleshooting in particular the section on WSL2?
The example should also run fine on your Windows host system.

Alternatively, with slight changes to the script you should also be able to run the viewer on Windows and the SDK inside WSL2 - I believe all that's needed for that is to change the `rr.init` call in the script to not spawn and instead run with `rr.connect()` to your local host. Then when you start the viewer manually on your host windows system, a the script should connect to the already running viewer. Depends a little bit on the network setup of your WSL though.
